/roar/global_planner_manager:
  ros__parameters:
    debug: true
    planner_name: "NavPlanner"
    planner_frequency: 0.1
    
    NavPlanner:
      path_step: 1.0

/roar/map_server:
  ros__parameters:
    use_sim_time: true 
    yaml_filename: "./src/launches/config/carla/parking/map.yaml"
    
/roar/lifecycle_manager_global_planning:
  ros__parameters:
    autostart: true
    use_sim_time: true
    node_names: ["/roar/global_planner_manager"]

/roar/lifecycle_manager_map_server:
  ros__parameters:
    autostart: true
    use_sim_time: true
    node_names: ["/roar/map_server"]